# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:fETTzGg2zcbfl9Tzi69rjsHLONkOO0AtTDxLw0CZ+Kk27Q7FG/PyDOHZq9Z3R8awqeSHh5lilNV50wOZ+O02FmHfcYaGsPDa2ODhb4x17iBbE1Q7MR0FCtGyTjYvqDH+AChgbYstu5jMn43ZCEmPcCxXF9U1B+4jRuDqMBsIRj6ralOoWZHKk0OBavG716+A7NSd44R7gdrmFmb3X/6uLIrv3UZVAUduf2i9HIKeOA==,iv:YyhQsvIJN1ctfb9EYos7lJYbx8F5X37gAcEDcgEQceY=,tag:iJCD28lp9SdmtVXFOzDaVw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h62ct3ewxu9hu8r4ny4p79qt6ct0qv2dnftl4nxut42ly6y7dfuq2fwfx6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbEppaUQ5cTVTS3NRak5p
        eXJvSUNSUUFNQzU5V0htSEdqN3lmVENpT213CkgxbFlMaGNBUHRmdlM3bzQ2Nisx
        am1ZWXQ3QkEvb1ZCdy84KzB0dDlnd00KLS0tIEt1WTVQL2pBMExsSDhhRXRtU2Fl
        R3BONWpjNGM1VkFRN2FIYjlHVC9jamsKYjf5oXOsrrFeLDOBGbqz9Z3y88yf4584
        6caXF3Ta37N/lsD4lGh3vpp9ZvEjL5waWMwAJ3yLb0oX4kxbntl0wg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T15:01:35Z"
  mac: ENC[AES256_GCM,data:iQniW9l8nQUpGb6Qp/oT+sQTkPv/X7n9zvJNcoM4mlrxwmYobcdBnz6JjKvAJO7WWTNYeNKZ9rC9PZk77x3P4LpBkX/zj6F0sZlodRUuFzyrbTYI5mL5duiZGznIIo1Olg33D/QaKZnKzqRiYJbnE7Y1Haf+TLZUd0Xe+ZqbM1E=,iv:xhX6B0ODm8Osvrl/j45sPRS476p626EcVrVmKqmc5Pw=,tag:h7ocOeqMneJdLW15wiNvtQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
