# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:tvoXQ7mF4/VDgHoHU0hEhrIm17rQZjl9co8oAuzRNw/cHEXpuI9/EA==,iv:c4CWTvgwdrEyj4wx5qoFMMEiiSlxIrI5lqin9a4s4Ps=,tag:WoyyGYOwA18siOzgLnNV5w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h62ct3ewxu9hu8r4ny4p79qt6ct0qv2dnftl4nxut42ly6y7dfuq2fwfx6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbm1pYVdhQ0g5TWJRaW55
        Sk5CRVM3eXB0VFY1eFdCWnROMlJyOEVoMlNNCm1EVG0wK0RGNXFlWUhMYUR2N3Mv
        TDQ4SERsMkpvRGVMR2hSNEt5cnM2eVUKLS0tIC9RTjR6a1ZOR0VFV28yUnpKaTM4
        aXJvN3JLclcxTTM4N3F2Zmh2TTRkZ2MKvR/okITuS2f6ASLlA/RKAvAR7UoAPH4r
        6S6IvJ7Gw3okPx/UvUWwrU1XJNZFFtsyHl+10uO1KH1CXMuhaz45oQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T15:32:38Z"
  mac: ENC[AES256_GCM,data:mh1eZVtIREjx32pEJSeaQuxeL+dwOTYOa18ISDRGdPg/NSGRZNFGnVQUrbsCAc6BTL7L8ush8L0ISBmwx0uKL8q9IxHg3lgMu1F4Wz2sAK1wDcjC1btXZHMCs7T3vs6yuoIXqlGvLO6DLL+a1yrVY4O13wem8na71Fq3Me9aj5w=,iv:iwVqijWf31pm3Rp2Ysg47xD6bJO2YoV1jEAYWAhAkbQ=,tag:wxbYCZBFUxXj16H/JZkKMg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
