apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:DQAwjcJ6fbR9n/YtnjboPSuIYrDYI+UxyZs5T0c507xWlkRJdr/rv3AuGozHvbMlvOFdEY8slfNydZoLWFLtzK95rIq0+4DwM1s=,iv:W6aK1+7XCz2W9pIg53wWR9SLUyCm9fomFo4g0tuuPqE=,tag:URKg5DLR1sKyyVPFQ1/02Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h62ct3ewxu9hu8r4ny4p79qt6ct0qv2dnftl4nxut42ly6y7dfuq2fwfx6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdHJwYzZZNHY3dFR6aG9u
        MGp2cGV2dkwzTXlmUUZCZnJWSVZ5TEN4SERZCnp0KzdyOEgvTUt1SU5uNnpPMWkw
        WU5QZS9QbXVmalo3YXdRZms0dVJqeHMKLS0tIE91OEZ4NzdTK3laNVdqbmhsODk3
        N1FMdWljdHhCU2dQaTNaakZCY2JtMjQKHWGri93Olw64W4HpfY8J0iogw8n1DGYA
        zPFsfcFR0b+/Y3LwpeEJhp1OdUIYOUQoJVJMgyKX4i1H3B2sbLgyYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T14:43:37Z"
  mac: ENC[AES256_GCM,data:+cgNdKcYhMp2W76AvazB1jg2ylsOCGVvLQqG9uErW5qcCrQinWzlnrnC0yDfeqtKj5ZDB4AkiSTAQh1YUNHQTWdceKO6ll4MLt/5JHxVVNngHFQ+Oa/PHSd8/Vk+L4MTLTqwSUUCraprWFH2WI+h8Ou32TCzEMAPoVq/aQmSU4E=,iv:EPmmXQIob1UwA6mUThi9FM85CwceXbMxklcSQWC4GrE=,tag:7uC/RYiDk9FP8tJ3NsEZeA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
